#!/usr/bin/python

import subprocess
import os
from sys import argv as arg

HOME = os.environ.get("HOME")
dir = f"{HOME}/.config/eww/scripts"

def capsLock_toggle():
    command = "cat /sys/class/leds/*::capslock/brightness | awk 'NR==1'"
    state = subprocess.run(command, shell=True, capture_output=True, text=True)
    state = int(state.stdout.strip())

    if state == 1:
        subprocess.run(f"{dir}/osd 󰬶 'Bloq Mayus ON' str  > /dev/null 2>&1  &", shell=True)
    elif state == 0:
        subprocess.run(f"{dir}/osd 󰬵 'Bloq Mayus OFF' str  > /dev/null 2>&1  &", shell=True)

def numLock_toggle():

    command = "cat /sys/class/leds/*::numlock/brightness | awk 'NR==1'"
    state = subprocess.run(command, shell=True, capture_output=True, text=True)
    state = int(state.stdout.strip())

    if state == 1:
        subprocess.run(f"{dir}/osd 󰎠 'Num Lock ON' str  > /dev/null 2>&1  &", shell=True)
    elif state == 0:
        subprocess.run(f"{dir}/osd 󱧓 'Num Lock OFF' str  > /dev/null 2>&1  &", shell=True)

if __name__ == "__main__":
    if arg[1] == "--numLock":
        numLock_toggle()
    elif arg[1] == "--capsLock":
        capsLock_toggle()
