#!/usr/bin/bash

choice="$1"
powered=$(bluetoothctl show | grep "Powered:" | awk '{print $2}')

bluetooth_on() {
    bluetoothctl power on
}

bluetooth_off() {
    bluetoothctl power off
}

bluetooth_icon() {    
    if [[ "$powered" == "no" ]]; then
        echo "󰂲"
    else
        echo "󰂯"
    fi
}

bluetooth_connected() {
    connected_device=$(bluetoothctl info | grep "Device" | awk '{print $2}')
    if [[ "$connected_device" == "(null)" ]]; then
        echo "Bluetooth"
    else
        echo "$connected_device"
    fi
}

bluetooth_status(){
    if [[ "$powered" == "no" ]]; then
        echo "disconnected"
    else
        echo "connected"
    fi

}

bluetooth_info(){
    json="{
        \"status\":\"$(bluetooth_status)\",
        \"name\":\"$(bluetooth_connected)\",
        \"icon\":\"$(bluetooth_icon)\"
        }"
    echo $json
}

if [[ $choice == "--info" ]]; then
    bluetooth_info
elif [[ $choice == "--on" ]]; then
    bluetooth_on
elif [[ $choice == "--off" ]]; then
    bluetooth_off
fi

