#!/bin/bash

dir="/home/$(whoami)/.config/eww/scripts"
backlight_device="/sys/class/backlight/$(ls /sys/class/backlight)"


icon() {
    local value="$1"
    if ((value < 30)); then
        echo "󰃞"
    elif ((value < 70)); then
        echo "󰃟"
    else
        echo "󰃠"
    fi
}

getValue() {
    current_brightness=$(brightnessctl get)
    max_brightness=$(brightnessctl max)
    new_brightness=$((100 * current_brightness / max_brightness))
    echo $new_brightness
}

if [[ $1 == "--get" ]]; then
    while inotifywait -e modify "$backlight_device/brightness" > /dev/null 2>&1; do
        icon=$(icon "$(getValue)")
        echo "{\"icon\": \"$icon\", \"value\": \"$(getValue)\"}"
    done

elif [[ $1 == "--set" ]]; then
    brightnessctl set "$2"%
    
elif [[ $1 == "--up" ]]; then
    brightnessctl set 10%+

    icon=$(icon "$(getValue)")
    
    zsh "$dir/osd" "$icon" "$(getValue)" "int" > /dev/null 2>&1 &

elif [[ $1 == "--down" ]]; then
    brightnessctl set 5%-

    icon=$(icon "$(getValue)")
    zsh "$dir/osd" "$icon" "$(getValue)" "int" > /dev/null 2>&1 &

fi
