#!/usr/bin/bash

param="$1"

current=$(eww get workspaces)

if [[ $param == "--down" ]]; then
    bspc desktop -f next.local

elif [[ $param == "--up" ]]; then
    bspc desktop -f prev.local

elif [[ $param == "--set" ]]; then
    bspc desktop -f $2

elif [[ $param == "--setnode" ]]; then
    eww close windowSwitcher
    bspc node -f $2
fi
