#!/usr/bin/python

from subprocess import PIPE
from subprocess import run as shellRun
from subprocess import getoutput as shellOut
from subprocess import Popen as shellPopen
import json
from sys import exit as sysexit

def get_workspace_info(monitor=None):

    # Almacenar los resultados de bspc para evitar llamadas innecesarias
    desktops = shellOut(f"bspc query -D --names").strip().split()
    focused_desktop = shellOut(f"bspc query -D -d focused --names").strip().split()
    occupied_desktops = shellOut(f"bspc query -D -d .occupied --names").strip().split()

    workspaces = []

    for d in desktops:
        if d in focused_desktop:
            state = "active"
        elif d in occupied_desktops:
            state = "inactive"
        else:
            state = "empty"

        workspaces.append({"id": d, "state": state})

    # Generar JSON
    return json.dumps(workspaces)

# Escuchar cambios en bspwm
proc = shellPopen(["bspc", "subscribe", "desktop_focus"], stdout=PIPE, text=True)

if __name__ == "__main__":
    while True:
        _ = proc.stdout.readline()
        workspace_info = get_workspace_info()
        shellRun(f"eww update workspaces={json.dumps(workspace_info)}", shell=True)