#!/usr/bin/python

import subprocess
import json
import sys
import os
import datetime


cache_dir = os.path.expanduser("~/.cache/eww")
jsonPath = os.path.join(cache_dir, "calendarEvents.json")

def create_cache_dir():
    if not os.path.exists(cache_dir):
        os.makedirs(cache_dir)

def update_cache(data):
    create_cache_dir()
    cached_data = get_cached_entries()
    if cached_data is None:
        cached_data = []
    cached_data.append(data)
    with open(jsonPath, "w") as file:
        json.dump(cached_data, file, indent=2)

def get_cached_entries():
    if os.path.exists(jsonPath):
        with open(jsonPath, "r") as file:
            try:
                return json.load(file)
            except json.JSONDecodeError:
                pass
    return []


if __name__ == "__main__":
    arg = None if len(sys.argv) < 2 else sys.argv[1]

    if arg == "--add":
        if len(sys.argv) >= 3:
            icon = "󰃮"
            content = sys.argv[2].split(";") if len(sys.argv) >= 2 else None

            if len(content) >= 3:
                if content[2] == "mid":
                    icon = "󰧓"
                elif content[2] == "high":
                    icon = "󰨱"

            event_dict = {
                "date": content[0],
                "content": content[1],
                "icon": icon
            }

            update_cache(event_dict)
        else:
            print("Uso: script.py --add 'fecha;contenido;prioridad'")

    elif arg == "--get":
        events = get_cached_entries()
        print(events)
