#!/usr/bin/bash

param="$1"

current=$(eww get workspaces)

if [[ $param == "--down" ]]; then
    hyprctl dispatch workspace +1

elif [[ $param == "--up" ]]; then
    hyprctl dispatch workspace -1

elif [[ $param == "--set" ]]; then
    hyprctl dispatch workspace $2

elif [[ $param == "--setnode" ]]; then
    eww close windowSwitcher
    bspc node -f $2
fi
