#!/usr/bin/bash


dir="/home/$(whoami)/.config/eww/scripts"

icon() {
    local value="$1"

    if [[ $value == "no"  ]]; then
        echo ""
    else
        echo ""
    fi
}

if [[ $1 == "--get" ]]; then
    pactl subscribe | grep --line-buffered "on source" | while read -r _ ; do
            vol=$(pactl get-source-volume @DEFAULT_SOURCE@ | grep -Po '[0-9]{1,3}(?=%)' | head -1)
            muted=$(pactl get-source-mute @DEFAULT_SOURCE@ | awk '{print $2}')
            icon=$(icon "$muted")
            echo "{\"icon\": \"$icon\", \"value\": \"$vol\"}"
    done
elif [[ $1 == "--set" ]]; then
    pactl set-source-volume @DEFAULT_SOURCE@ $2%
    
elif [[ $1 == "--up" ]]; then
    pactl set-source-volume @DEFAULT_SOURCE@ +10%

elif [[ $1 == "--down" ]]; then
    pactl set-source-volume @DEFAULT_SOURCE@ -10%
    
elif [[ $1 == "--toggle" ]]; then
    pactl set-source-mute @DEFAULT_SOURCE@ toggle

    muted=$(pactl get-source-mute @DEFAULT_SOURCE@ | awk '{print $2}')
    vol=$(pactl get-source-volume @DEFAULT_SOURCE@ | grep -Po '[0-9]{1,3}(?=%)' | head -1)
    icon=$(icon "$muted")

    zsh "$dir/osd" "$icon" "$vol" "int" > /dev/null 2>&1 &

fi
