#!/usr/bin/bash

STATE=$(eww windows | grep notifpopup | awk '{print substr ($0, 0, 1)}')

if [[ $1 == '--close' ]]; then
	if [[ $STATE == '*' ]]; then
		eww close notifpopup
	fi
else

	if [[ $STATE != '*' ]]; then
		eww open notifpopup 
	fi

	sleep 3

	if [[ $STATE == '*' ]]; then
		eww close notifpopup
	fi

fi