#!/usr/bin/bash

choice=$1

pacman_packages() {
    echo "$(pacman -Qq | wc -l)"
}

upTime_h(){
    hour="$(uptime -p | awk '{print $2 "h"}')"
    if [[ "$hour" == "h" ]]; then 
        echo ""
    else 
        echo "$hour"
    fi
}

upTime_m(){
    min="$(uptime -p | awk '{print $4 "m"}')"
    echo "$min"
}

userHost() {
    echo "$(whoami)@$(hostnamectl --json=pretty | jq .Hostname  | sed 's/"//g')"
}

Host() {
    echo "@$(hostnamectl --json=pretty | jq .Hostname  | sed 's/"//g')"
}

User() {
    echo "$(whoami)"
}


kernel(){
    echo "$(uname -r)"

}

systemCPU(){
    cpu="$(lscpu | grep "Model name" | cut -d':' -f2- | sed -e 's/^[ \t]*//' | awk '{print $3}')"
    echo "$cpu"
}

systemGPU(){
    gpu_nvidia="$(lspci | grep -i "VGA" | grep -i "NVIDIA" | awk -F ': ' '{print $2}')"
    
    if [ -n "$gpu_nvidia" ]; then
        gpu_name="$(echo "$gpu_nvidia" | sed -n 's/.*\bGTX \([0-9]* [A-Za-z]*\).*/GTX \1/p')"
        echo "$gpu_name"
    else
        gpu_intel="$(lspci | grep -i "VGA" | grep -i "Intel" | awk -F ': ' '{print $2}')"
        echo "$gpu_intel"
    fi
}

if [[ $choice == "--pacman" ]]; then
    pacman_packages; 
elif [[ $choice == "--userHost" ]]; then
    userHost
elif [[ $choice == "--user" ]]; then
    User
elif [[ $choice == "--host" ]]; then
    Host

elif [[ $choice == "--uptimeH" ]]; then
    upTime_h
elif [[ $choice == "--uptimeM" ]]; then
    upTime_m
elif [[ $choice == "--uptime" ]]; then
    echo $(uptime -p)
elif [[ $choice == "--kernel" ]]; then
    kernel
elif [[ $choice == "--systemCPU" ]]; then
    systemCPU
elif [[ $choice == "--systemGPU" ]]; then
    systemGPU
else
    echo "Usage ./stats --parameter"
fi