#!/usr/bin/bash
# https://github.com/Axarva/dotfiles-2.0/

tmp_weather="$HOME/.cache/eww/weather"
tmp_weather_stat=$tmp_weather/weather-stat
tmp_weather_degree=$tmp_weather/weather-degree
tmp_weather_quote=$tmp_weather/weather-quote
tmp_weather_hex=$tmp_weather/weather-hex
tmp_weather_icon=$tmp_weather/weather-icon

if [ ! -d $tmp_weather ]; then
        mkdir -p $tmp_weather
fi

# Put in your api and stuff link here 
# If you dunno, head to openweathermap.org, and make and account 
#(completely free I swear, and then get your API Key and  your City ID)
# I wish I was smart enough to do it like Elena, but this is the top I could do lol

KEY=""
ID=""
UNIT="metric" #Options are 'metric' and 'imperial'
weather=$(curl -sf "http://api.openweathermap.org/data/2.5/weather?APPID="$KEY"&id="$ID"&units="$UNIT"")

if [ ! -z "$weather" ]; then
    weather_temp=$(echo "$weather" | jq ".main.temp" | cut -d "." -f 1)
    weather_icon_code=$(echo "$weather" | jq -r ".weather[].icon" | head -1)
	weather_description=$(echo "$weather" | jq -r ".weather[].description" | head -1 | sed -e "s/\b\(.\)/\u\1/g")


    if [[ "$weather_icon_code" == "50d" || "$weather_icon_code" == "40d" ]]; then
		weather_icon=""
        weather_quote1="Forecast says it's misty"
        weather_quote2="Make sure you don't get lost on your way..."
        weather_hex="#a7b8b2"

    elif [[ "$weather_icon_code" == "50n" || "$weather_icon_code" == "40n"   ]]; then
        weather_icon=""
        weather_quote1="Forecast says it's a misty night"
        weather_quote2="Don't go anywhere tonight or you might get lost..."
        weather_hex="#84afdb"

    elif [[ "$weather_icon_code" == "01d"  ]]; then
        weather_icon="󰖙"
        weather_quote1="It's a sunny day, gonna be fun!"
        weather_quote2="Don't go wandering all by yourself though..."
        weather_hex="#ffd86b"

    elif [[ "$weather_icon_code" == "01n"  ]]; then
        weather_icon=""
        weather_quote1="It's a clear night"
        weather_quote2="You might want to take a evening stroll to relax..."
        weather_hex="#fcdcf6"
    elif [[ "$weather_icon_code" == "02d" || "$weather_icon_code" == "03d" ||  "$weather_icon_code" == "04d" ]]; then
        weather_icon=""
        weather_quote1="It's  cloudy, sort of gloomy"
        weather_quote2="You'd better get a book to read..."
        weather_hex="#adadff"
    elif [[ "$weather_icon_code" == "02n" || "$weather_icon_code" == "03n" || "$weather_icon_code" == "04n" ]]; then
        weather_icon=""
        weather_quote1="It's a cloudy night"
        weather_quote2="How about some hot chocolate and a warm bed?"
        weather_hex="#adadff"
    elif [[ "$weather_icon_code" == "09d" || "$weather_icon_code" == "10d"  ]]; then
        weather_icon=""
        weather_quote1="It's rainy, it's a great day!"
        weather_quote2="Get some ramen and watch as the rain falls..."
        weather_hex="#6b95ff"
    elif [[ "$weather_icon_code" == "09n" || "$weather_icon_code" == "10n" ]]; then
        weather_icon=""
        weather_quote1="It's gonna rain tonight it seems"
        weather_quote2="Make sure your clothes aren't still outside..."
        weather_hex="#6b95ff"

    elif [[ "$weather_icon_code" == "11d"  ]]; then
        weather_icon=""
        weather_quote1="There's storm for forecast today"
        weather_quote2="Make sure you don't get blown away..."
        weather_hex="#ffeb57"

    elif [[ "$weather_icon_code" == "11n"  ]]; then
        weather_icon=""
        weather_quote1="There's gonna be storms tonight"
        weather_quote2="Make sure you're warm in bed and the windows are shut..."
        weather_hex="#ffeb57"

    elif [[ "$weather_icon_code" == "13d"  ]]; then
        weather_icon=""
        weather_quote1="It's gonna snow today"
        weather_quote2="You'd better wear thick clothes and make a snowman as well!"
        weather_hex="#e3e6fc"

    elif [[ "$weather_icon_code" == "13n"  ]]; then
        weather_icon=""
        weather_quote1="It's gonna snow tonight"
        weather_quote2="Make sure you get up early tomorrow to see the sights..."
        weather_hex="#e3e6fc"

    else 
        weather_icon="󰖐"
        weather_quote1="Sort of odd, I don't know what to forecast"
        weather_quote2="Make sure you have a good time!"
        weather_hex="#adadff"
    fi
          
        json="{\"icon\": \"$weather_icon\",\"description\": \"$weather_description\",\"temperature\": \"$weather_temp°C\",\"quoteOne\": \"$weather_quote1\",\"quoteTwo\": \"$weather_quote2\",\"hex\": \"$weather_hex\"}"

        echo $json
        eww update weather="$json"
    else
        json="{\"icon\": \"󰖐\",\"description\": \"Weather Unavailable\",\"temperature\": \"-\",\"quoteOne\": \"Ah well, no weather huh?\",\"quoteTwo\":\"Even if there's no weather, it's gonna be a great day!\",\"hex\": \"#adadff\"}"
        echo $json
        eww update weather="$json"
fi