#!/bin/sh

# Use brillo to logarithmically adjust laptop screen brightness
# and send a notification displaying the current brightness level after.

send_notification() {
    brightness=$(printf "%.0f\n" "$(brillo -G)")
    echo "Current brightness: $brightness"  # Debug line
    swaync-client -t -i "brightness-$1" "Brightness: $brightness%"
}

echo "Script called with argument: $1"  # Debug line

case $1 in
up)
    brillo -A 5 -q
    echo "Increased brightness"  # Debug line
    send_notification "$1"
    ;;
down)
    brillo -U 5 -q
    echo "Decreased brightness"  # Debug line
    send_notification "$1"
    ;;
*)
    echo "Usage: $0 {up|down}"  # Usage instructions
    ;;
esac
